[package]
name = "rust_json_parser"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "json_parser"
path = "src/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
